# Generated by Django 6.0 on 2025-12-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('capacity', models.FloatField(default=100.0)),
                ('oee_target', models.FloatField(default=90.0)),
                ('cost_per_hour', models.FloatField(default=0.0)),
            ],
        ),
    ]
